services:
  db:
    image: postgres:15-alpine
    container_name: skill-mentor-db
    environment:
      POSTGRES_DB: skillmentor-2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432" # Keep this for database access (pgAdmin)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: skill-mentor-service:lts
    container_name: skill-mentor-backend
    ports:
      - "8081:8081"  # This maps your Windows 8081 to the Container 8081
    environment:
      - SERVER_PORT=8081
      - DB_URL=jdbc:postgresql://db:5432/skillmentor-2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db

volumes:
  postgres_data: